Class {
	#name : #BDItem,
	#superclass : #Object,
	#instVars : [
		'title',
		'notes',
		'sortedAs',
		'base',
		'entryCreationDate',
		'entryNumber',
		'editor',
		'year',
		'mainSerie',
		'serie',
		'original',
		'depotLegal',
		'castermanNote',
		'authors',
		'ISBN',
		'number',
		'numberOnCover',
		'serieComplete',
		'coverPictureName',
		'collection'
	],
	#category : #Comix
}

{ #category : #accessing }
BDItem >> authors: aValue [
	authors := aValue

]

{ #category : #accessing }
BDItem >> castermanNote: aValue [
	castermanNote := aValue

]

{ #category : #accessing }
BDItem >> coverPictureName: aValue [
	coverPictureName := aValue

]

{ #category : #accessing }
BDItem >> editor: aValue [
	editor := aValue

]

{ #category : #accessing }
BDItem >> entryCreationDate: aValue [
	entryCreationDate := aValue

]

{ #category : #accessing }
BDItem >> entryNumber: aValue [
	entryNumber := aValue

]

{ #category : #accessing }
BDItem >> notes: aValue [
	notes := aValue

]

{ #category : #accessing }
BDItem >> number: aValue [
	number := aValue

]

{ #category : #accessing }
BDItem >> original: aValue [
	original := aValue

]

{ #category : #accessing }
BDItem >> serie: aValue [
	serie := aValue

]

{ #category : #accessing }
BDItem >> serieComplete: aValue [
	serieComplete := aValue

]

{ #category : #accessing }
BDItem >> sortedAs: aValue [
	sortedAs := aValue

]

{ #category : #accessing }
BDItem >> title: aValue [
	title := aValue

]

{ #category : #accessing }
BDItem >> year: aValue [
	year := aValue

]
