Class {
	#name : #BDItem,
	#superclass : #Object,
	#instVars : [
		'title',
		'notes',
		'sortedAs',
		'base',
		'entryCreationDate',
		'entryNumber',
		'editor',
		'year',
		'mainSerie',
		'serie',
		'original',
		'depotLegal',
		'castermanNote',
		'authors',
		'ISBN',
		'number',
		'numberOnCover',
		'serieComplete',
		'coverPictureName',
		'collection'
	],
	#category : #Comix
}

{ #category : #accessing }
BDItem >> authors [
	^ authors

]

{ #category : #accessing }
BDItem >> authors: aValue [
	authors := aValue

]

{ #category : #accessing }
BDItem >> castermanNote [
	^ castermanNote

]

{ #category : #accessing }
BDItem >> castermanNote: aValue [
	castermanNote := aValue

]

{ #category : #accessing }
BDItem >> collection [
	^ collection

]

{ #category : #accessing }
BDItem >> collection: aValue [
	collection := aValue

]

{ #category : #accessing }
BDItem >> coverPictureName [
	^ coverPictureName

]

{ #category : #accessing }
BDItem >> coverPictureName: aValue [
	coverPictureName := aValue

]

{ #category : #accessing }
BDItem >> depotLegal [
	^ depotLegal

]

{ #category : #accessing }
BDItem >> depotLegal: aValue [
	depotLegal := aValue

]

{ #category : #accessing }
BDItem >> editor [
	^ editor

]

{ #category : #accessing }
BDItem >> editor: aValue [
	editor := aValue

]

{ #category : #accessing }
BDItem >> entryCreationDate [
	^ entryCreationDate

]

{ #category : #accessing }
BDItem >> entryCreationDate: aValue [
	entryCreationDate := aValue

]

{ #category : #accessing }
BDItem >> entryNumber [
	^ entryNumber

]

{ #category : #accessing }
BDItem >> entryNumber: aValue [
	entryNumber := aValue

]

{ #category : #accessing }
BDItem >> mainSerie [
	^ mainSerie

]

{ #category : #accessing }
BDItem >> mainSerie: aValue [
	mainSerie := aValue

]

{ #category : #accessing }
BDItem >> notes [
	^ notes

]

{ #category : #accessing }
BDItem >> notes: aValue [
	notes := aValue

]

{ #category : #accessing }
BDItem >> number [
	^ number

]

{ #category : #accessing }
BDItem >> number: aValue [
	number := aValue

]

{ #category : #accessing }
BDItem >> numberOnCover [
	^ numberOnCover

]

{ #category : #accessing }
BDItem >> numberOnCover: aValue [
	numberOnCover := aValue

]

{ #category : #accessing }
BDItem >> original [
	^ original

]

{ #category : #accessing }
BDItem >> original: aValue [
	original := aValue

]

{ #category : #accessing }
BDItem >> serie [
	^ serie

]

{ #category : #accessing }
BDItem >> serie: aValue [
	serie := aValue

]

{ #category : #accessing }
BDItem >> serieComplete [
	^ serieComplete

]

{ #category : #accessing }
BDItem >> serieComplete: aValue [
	serieComplete := aValue

]

{ #category : #accessing }
BDItem >> sortedAs [
	^ sortedAs

]

{ #category : #accessing }
BDItem >> sortedAs: aValue [
	sortedAs := aValue

]

{ #category : #accessing }
BDItem >> title [
	^ title

]

{ #category : #accessing }
BDItem >> title: aValue [
	title := aValue

]

{ #category : #accessing }
BDItem >> year [
	^ year

]

{ #category : #accessing }
BDItem >> year: aValue [
	year := aValue

]
