Class {
	#name : #CXTodo,
	#superclass : #Object,
	#category : #'Comix-Model'
}

{ #category : #'accessing structure variables' }
CXTodo >> a [

	" add test for sortedAs 
	for bd number should use numberOnCover and not sortedAs
	we should revisit it for strange collection"
]

{ #category : #'accessing structure variables' }
CXTodo >> b [

	" should model range based series such as manga
	to say that we have 1 to 11, 13, 15 to 18"
]

{ #category : #'accessing structure variables' }
CXTodo >> c [

	" should model series explicitly from an item ie not as strings."
]
